apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: app-desafio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: brunosantos88/otel-app-banco:v1
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: temperaturas
            - name: POSTGRES_USER
              value: admin
            - name: POSTGRES_PASSWORD
              value: admin123
          volumeMounts: # montagem de volume 
          - name: postgres-storage
            mountPath: /var/lib/postgresql/data
      volumes: #volume setado.
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-pvc
---
# apiVersion: v1
# kind: Service
# metadata:
#   name: postgres
#   namespace: app-desafio
# spec:
#   type: ClusterIP
#   selector:
#     app: postgres
#   ports:
#     - port: 5432
#       targetPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: app-desafio
spec:
  clusterIP: None
  selector:
    app: postgres
  ports:
  - port: 5432
    targetPort: 5432