apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: app-desafio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: docker.io/brunosantos88/otel-app-backend:10