apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: app-backend
spec:
  type: ClusterIP
  selector:
    app: backend
  ports:
    - name: backend
      protocol: TCP
      port: 5000
      targetPort: 5000