apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: app-desafio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: brunosantos88/otel-app-banco:v1
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: mydb
            - name: POSTGRES_USER
              value: user
            - name: POSTGRES_PASSWORD
              value: password
          volumeMounts: #montagem
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
      volumes: 
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: app-desafio
spec:
  type: NodePort
  selector:
    app: postgres
  ports:
  - protocol: TCP
    port: 5432         
    targetPort: 5432
    nodePort: 30003