apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: app-desafio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: brunosantos88/otel-app-frontend:v5.1
        ports:
        - containerPort: 80
        env:
        - name: APP_BACKEND_URL      
          value: "http://backend-service:5000"
        - name: BACKEND_PORT
          value: "5000"

---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: app-desafio
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
  - name: frontend
    protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30002
