apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-ingress
  namespace: app-desafio
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: "temperatura.com"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend
            port:
              number: 80
