apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: app-desafio
spec:
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: brunosantos88/otel-app-backend:v7
        ports:
            - name: http
              containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    app: backend
    tier: backend
  ports:
  - protocol: TCP
    port: 80
    targetPort: http
...
