apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: app-desafios
spec:
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: docker.io/brunosantos88/otel-app-frontend:10