apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-frontend
  namespace: frontend
spec:
  replicas: 10
  selector:
    matchLabels:
      app: nginx-frontend
  template:
    metadata:
      labels:
        app: nginx-frontend
    spec:
      nodeSelector:
        kubernetes.io/hostname: minikube-m02
      containers:
      - name: nginx
        image: nginx:latest
        resources:
          requests:
            memory: "20Mi"
            cpu: "10m"
          limits:
            memory: "100Mi"
            cpu: "50m"
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-frontend
  namespace: frontend
spec:
  selector:
    app: nginx-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP 